Separates structure on Homepage
Signed-off-by: Georgios Tsotsos <tsotsos@gmail.com>

diff --git a/cluster/apps/home/home-assistant/values.yaml b/cluster/apps/home/home-assistant/values.yaml
--- a/cluster/apps/home/home-assistant/values.yaml
+++ b/cluster/apps/home/home-assistant/values.yaml
@@ -5,7 +5,7 @@ persistence:
   storageClass: longhorn
 additionalVolumes:
     - configMap:
-        defaultMode: 0777
+        defaultMode: 0755
         name: extra-config
       name: extra-config
 additionalMounts:
@@ -63,7 +63,54 @@ configuration:
       automation: !include automations.yaml
       script: !include scripts.yaml
       scene: !include scenes.yaml
+  initScript: |-
+    #!/bin/bash
+    set -e
 
+    # Check if the configuration file exists
+    if [ ! -f /config/configuration.yaml ]; then
+      echo "Configuration file not found, creating a new one"
+      cp /config-templates/configuration.yaml /config/configuration.yaml
+    fi
+
+    # Check if the force init is enabled
+    forceInit="{{ .Values.configuration.forceInit }}"
+    if [ "$forceInit" = "true" ]; then
+      echo "Force init is enabled, overwriting the configuration file"
+      current_time=$(date +%Y%m%d_%H%M%S)
+      echo "Backup the current configuration file to configuration.yaml.$current_time"
+      cp /config/configuration.yaml /config/configuration.yaml.$current_time
+      echo "The current configuration file will be merged with the default configuration file with this content:"
+      cat /config-templates/configuration.yaml
+      if [[ ! -s /config/configuration.yaml ]]; then
+        # If /config/configuration.yaml is empty, use the content of /config-templates/configuration.yaml
+        cat /config-templates/configuration.yaml > /config/configuration.yaml
+      else
+        # Perform the merge operation if /config/configuration.yaml is not empty
+        yq eval-all --inplace 'select(fileIndex == 0) *d select(fileIndex == 1)' /config/configuration.yaml /config-templates/configuration.yaml
+      fi
+    fi
+
+    # Check if the automations file exists
+    if [ ! -f /config/automations.yaml ]; then
+      echo "Automations file not found, creating a new one"
+      touch /config/automations.yaml
+      echo "[]" >> /config/automations.yaml
+    fi
+
+    # Check if the scripts file exists
+    if [ ! -f /config/scripts.yaml ]; then
+      echo "Scripts file not found, creating a new one"
+      touch /config/scripts.yaml
+    fi
+
+    # Check if the scenes file exists
+    if [ ! -f /config/scenes.yaml ]; then
+      echo "Scenes file not found, creating a new one"
+      touch /config/scenes.yaml
+    fi
+    # make all files writeable from vscode - this is a workaround for the vscode addon.
+    chmod 755 /config/*
 addons:
   codeserver:
     enabled: true
